steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/ruby:$_TAG', '.']
  - name: 'gcr.io/gcp-runtimes/structure_test'
    args: ['--image', 'gcr.io/$PROJECT_ID/ruby:$_TAG', '-v',
           '--config', '/workspace/structure-test.json']

images:
  - 'gcr.io/$PROJECT_ID/ruby:$_TAG'
