steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['pull', 'gcr.io/$_BASE_PROJECT_ID/ruby:$_TAG']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['tag', 'gcr.io/$_BASE_PROJECT_ID/ruby:$_TAG', 'ruby-base']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/ruby/build-tools:$_TAG', '.']

images:
  - 'gcr.io/$PROJECT_ID/ruby/build-tools:$_TAG'
